name: /work2/noaa/wrfruc/murdzek/conda/miniforge_hercules/env/my_py
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - aiobotocore=2.21.1=pyhd8ed1ab_0
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.11.13=py39h9399b63_0
  - aioitertools=0.12.0=pyhd8ed1ab_1
  - aiosignal=1.3.2=pyhd8ed1ab_0
  - arm_pyart=1.19.2=py39h8cd3c5a_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-timeout=5.0.1=pyhd8ed1ab_1
  - attrs=25.2.0=pyh71513ae_0
  - blosc=1.21.5=hc2324a3_1
  - bokeh=2.4.3=pyhd8ed1ab_3
  - boost-cpp=1.78.0=h5adbc97_2
  - botocore=1.37.1=pyge38_1234567_0
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - brotli-python=1.1.0=py39hf88036b_2
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.4=hb9d3cd8_0
  - ca-certificates=2025.1.31=hbcca054_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.16.0=ha61ee94_1014
  - cartopy=0.23.0=py39h3b40f6f_2
  - certifi=2025.1.31=pyhd8ed1ab_0
  - cffi=1.17.1=py39h15c3d72_0
  - cfitsio=4.2.0=hd9d235c_0
  - cftime=1.6.4=py39hf3d9206_1
  - charset-normalizer=3.4.1=pyhd8ed1ab_0
  - click=8.1.8=pyh707e725_0
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - cmweather=0.3.2=pyhd8ed1ab_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.0=py39h74842e3_2
  - curl=8.1.2=h409715c_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - cytoolz=1.0.1=py39h8cd3c5a_0
  - dask=2023.3.0=pyhd8ed1ab_0
  - dask-core=2023.3.0=pyhd8ed1ab_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - distributed=2023.3.0=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - executing=2.1.0=pyhd8ed1ab_1
  - expat=2.6.4=h5888daf_0
  - flexcache=0.3=pyhd8ed1ab_1
  - flexparser=0.4=pyhd8ed1ab_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.56.0=py39h9399b63_0
  - freeglut=3.2.2=h9c3ff4c_1
  - freetype=2.12.1=h267a509_2
  - freexl=1.0.6=h166bdaf_1
  - frozenlist=1.5.0=py39h9399b63_1
  - fsspec=2025.3.0=pyhd8ed1ab_0
  - g2clib=1.6.0=3
  - geos=3.11.1=h27087fc_0
  - geotiff=1.7.1=h7a142b4_6
  - gettext=0.23.1=h5888daf_0
  - gettext-tools=0.23.1=h5888daf_0
  - giflib=5.2.2=hd590300_0
  - h2=4.2.0=pyhd8ed1ab_0
  - h5netcdf=1.6.1=pyhd8ed1ab_0
  - h5py=3.7.0=nompi_py39h817c9c5_102
  - hdf4=4.2.15=h9772cbc_5
  - hdf5=1.12.2=nompi_h4df4325_101
  - hdfeos2=2.20=hb955811_1002
  - hdfeos5=5.1.16=hc55c121_12
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=70.1=h27087fc_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-resources=6.5.2=pyhd8ed1ab_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - iniconfig=2.0.0=pyhd8ed1ab_1
  - ipython=8.18.1=pyh707e725_3
  - jasper=2.0.33=h0ff4b12_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - jmespath=1.0.1=pyhd8ed1ab_1
  - jpeg=9e=h166bdaf_2
  - json-c=0.16=hc379101_0
  - kealib=1.5.0=ha7026e8_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.7=py39h74842e3_0
  - krb5=1.20.1=h81ceb04_0
  - lat_lon_parser=1.3.1=pyhd8ed1ab_1
  - lcms2=2.15=hfd0df8a_0
  - ld_impl_linux-64=2.43=h712a8e2_4
  - lerc=4.0.0=h27087fc_0
  - libaec=1.1.3=h59595ed_0
  - libasprintf=0.23.1=h8e693c7_0
  - libasprintf-devel=0.23.1=h8e693c7_0
  - libblas=3.9.0=31_h59b9bed_openblas
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcblas=3.9.0=31_he106b2a_openblas
  - libcurl=8.1.2=h409715c_0
  - libdeflate=1.17=h0b41bf4_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.6.4=h5888daf_0
  - libffi=3.4.6=h2dba641_0
  - libgcc=14.2.0=h767d61c_2
  - libgcc-ng=14.2.0=h69a702a_2
  - libgdal=3.6.2=h6c674c2_9
  - libgettextpo=0.23.1=h5888daf_0
  - libgettextpo-devel=0.23.1=h5888daf_0
  - libgfortran=14.2.0=h69a702a_2
  - libgfortran-ng=14.2.0=h69a702a_2
  - libgfortran5=14.2.0=hf1ad2bd_2
  - libglib=2.78.1=hebfc3b9_0
  - libglu=9.0.0=he1b5a44_1001
  - libgomp=14.2.0=h767d61c_2
  - libiconv=1.18=h4ce23a2_1
  - libjpeg-turbo=2.1.4=h166bdaf_0
  - libkml=1.3.0=h01aab08_1016
  - liblapack=3.9.0=31_h7ac8fdf_openblas
  - liblzma=5.6.4=hb9d3cd8_0
  - liblzma-devel=5.6.4=hb9d3cd8_0
  - libnetcdf=4.9.1=nompi_h34a3ff0_101
  - libnghttp2=1.58.0=h47da74e_0
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.29=pthreads_h94d23a6_0
  - libpng=1.6.43=h2797004_0
  - libpq=15.2=hb675445_0
  - librttopo=1.1.0=ha49c73b_12
  - libspatialite=5.0.1=h221c8f1_23
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx=14.2.0=h8f9b012_2
  - libstdcxx-ng=14.2.0=h4852527_2
  - libtiff=4.5.0=h6adf6a1_2
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.13=h7f98852_1004
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.10.3=hca2bb57_4
  - libzip=1.10.1=h2629f0a_3
  - libzlib=1.2.13=h4ab18f5_6
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4=4.3.3=py39hd7df8f7_1
  - lz4-c=1.9.4=hcb278e6_0
  - markupsafe=3.0.2=py39h9399b63_1
  - matplotlib-base=3.9.4=py39h16632d1_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mda-xdrlib=0.2.0=pyhd8ed1ab_1
  - metpy=1.6.3=pyhd8ed1ab_1
  - msgpack-python=1.1.0=py39h74842e3_0
  - multidict=6.1.0=py39h9399b63_2
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.5=h2d0b736_3
  - netcdf4=1.6.3=nompi_py39h8b3a7bc_100
  - nspr=4.36=h5888daf_0
  - nss=3.100=hca3bf56_0
  - numpy=1.26.4=py39h474f0d3_0
  - open-radar-data=0.4.3=pyhd8ed1ab_0
  - openjpeg=2.5.0=hfec8fc6_2
  - openssl=3.1.8=h7b32b05_0
  - packaging=24.2=pyhd8ed1ab_2
  - pandas=2.2.3=py39h3b40f6f_2
  - parso=0.8.4=pyhd8ed1ab_1
  - partd=1.4.2=pyhd8ed1ab_0
  - pcre2=10.40=hc3806b6_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=9.4.0=py39h2320bf1_1
  - pint=0.24.4=pyhd8ed1ab_1
  - pip=25.0.1=pyh8b19718_0
  - pixman=0.44.2=h29eaf8c_0
  - platformdirs=4.3.6=pyhd8ed1ab_1
  - pluggy=1.5.0=pyhd8ed1ab_1
  - pooch=1.8.2=pyhd8ed1ab_1
  - poppler=23.03.0=h091648b_0
  - poppler-data=0.4.12=hd8ed1ab_0
  - postgresql=15.2=h3248436_0
  - proj=9.1.1=h8ffa02c_2
  - prompt-toolkit=3.0.50=pyha770c72_0
  - propcache=0.2.1=py39h9399b63_1
  - psutil=7.0.0=py39h8cd3c5a_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.1=pyhd8ed1ab_0
  - pynio=1.5.5=py39h086e2a9_22
  - pyparsing=3.2.1=pyhd8ed1ab_0
  - pyproj=3.5.0=py39hf8a5840_0
  - pyshp=2.3.1=pyhd8ed1ab_1
  - pysocks=1.7.1=pyha55dd90_7
  - pytest=8.3.5=pyhd8ed1ab_0
  - python=3.9.18=h0755675_0_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-tzdata=2025.1=pyhd8ed1ab_0
  - python_abi=3.9=5_cp39
  - pytz=2024.1=pyhd8ed1ab_0
  - pyyaml=6.0.2=py39h9399b63_2
  - qhull=2020.2=h434a139_5
  - readline=8.2=h8c095d6_2
  - requests=2.32.3=pyhd8ed1ab_1
  - s3fs=2025.3.0=pyhd8ed1ab_0
  - scipy=1.13.1=py39haf93ffa_0
  - setuptools=75.8.2=pyhff2d567_0
  - setuptools-scm=8.2.0=pyhd8ed1ab_0
  - setuptools_scm=8.2.0=hd8ed1ab_0
  - shapely=2.0.1=py39hc9151fd_0
  - six=1.17.0=pyhd8ed1ab_0
  - snappy=1.2.1=h8bd8927_1
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - sqlite=3.46.0=h6d4b2fc_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tblib=3.0.0=pyhd8ed1ab_1
  - tiledb=2.13.2=hd532e3d_0
  - tk=8.6.13=noxft_h4845f30_101
  - tomli=2.2.1=pyhd8ed1ab_1
  - toolz=1.0.0=pyhd8ed1ab_1
  - tornado=6.4.2=py39h8cd3c5a_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.12.2=hd8ed1ab_1
  - typing_extensions=4.12.2=pyha770c72_1
  - tzcode=2025a=hb9d3cd8_0
  - tzdata=2025a=h78e105d_0
  - unicodedata2=16.0.0=py39h8cd3c5a_0
  - uriparser=0.9.8=hac33072_0
  - urllib3=1.26.19=pyhd8ed1ab_0
  - versioneer=0.29=pyhd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - wrapt=1.17.2=py39h8cd3c5a_0
  - xarray=2024.3.0=pyhd8ed1ab_0
  - xarray-datatree=0.0.14=pyhd8ed1ab_0
  - xerces-c=3.2.4=h55805fa_1
  - xmltodict=0.14.2=pyhd8ed1ab_1
  - xorg-fixesproto=5.0=hb9d3cd8_1003
  - xorg-inputproto=2.3.2=hb9d3cd8_1003
  - xorg-kbproto=1.0.7=hb9d3cd8_1003
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.4=h0b41bf4_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h7f98852_0
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=hb9d3cd8_1003
  - xorg-xextproto=7.3.0=hb9d3cd8_1004
  - xorg-xproto=7.0.31=hb9d3cd8_1008
  - xradar=0.7.0=pyhd8ed1ab_0
  - xz=5.6.4=hbcc6ac9_0
  - xz-gpl-tools=5.6.4=hbcc6ac9_0
  - xz-tools=5.6.4=hb9d3cd8_0
  - yaml=0.2.5=h7f98852_2
  - yarl=1.18.3=py39h9399b63_1
  - zict=3.0.0=pyhd8ed1ab_1
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.2.13=h4ab18f5_6
  - zstandard=0.23.0=py39h8cd3c5a_1
  - zstd=1.5.6=ha6fb4c9_0
prefix: /work2/noaa/wrfruc/murdzek/conda/miniforge_hercules/env/my_py
